core/urls.py
from django.urls import include, path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="base"),
    path(
        "products/",
        include(
            [
                path("", views.products_home, name="products"),
                path("summary/", views.products_summary, name="products-summary"),
                path("load-products/", views.load_products, name="load-products"),
                path(
                    "<uuid:product_id>/update-stocks",
                    views.update_product_stock,
                    name="update-product-stock",
                ),
                path("import-products/", views.import_products, name="import-products"),
                path(
                    "import-products/do",
                    views.do_import_products,  # type: ignore
                    name="do-import-products",
                ),
                path(
                    "import-products/track_progress/<task_id>",
                    views.track_import_progress,
                    name="import-products-status",
                ),
                path(
                    "remove-products/",
                    views.remove_all_products,
                    name="remove-products",
                ),
                path(
                    "remove-products/question",
                    views.remove_all_products_question,
                    name="remove-products-question",
                ),
                path(
                    "remove-products/do",
                    views.do_remove_products,
                    name="do-remove-products",
                ),
                path(
                    "remove-products/track_progress/<task_id>",
                    views.track_remove_product_progress,
                    name="remove-products-status",
                ),
                path(
                    "get-product-action-buttons",
                    views.get_product_action_buttons,
                    name="get-product-action-buttons",
                ),
                path(
                    "add-product",
                    views.add_product,
                    name="add-product",
                ),
                path(
                    "<uuid:product_id>/update-product",
                    views.update_product,
                    name="update-product",
                ),
                path(
                    "<uuid:product_id>/remove-product",
                    views.remove_a_product_question,
                    name="remove-a-product-question",
                ),
                path(
                    "<uuid:product_id>/remove-product/do",
                    views.do_remove_a_product,
                    name="do-remove-a-product",
                ),
                path("out-of-stock/", views.out_of_stock, name="out-of-stock"),
                path(
                    "out-of-stock/load",
                    views.load_out_of_stock,
                    name="load-out-of-stock",
                ),
            ]
        ),
    ),
    path(
        "orders/",
        include(
            [
                path("", views.orders, name="orders"),
                path("sell-products/", views.orders_products, name="orders-products"),
                path(
                    "sell-products/load/",
                    views.load_orders_products,
                    name="load-orders-products",
                ),
                path("make-order/", views.make_order, name="make-order"),
                path("check-orders/", views.today_orders, name="today-orders"),
                path(
                    "check-orders/days",
                    views.fetch_days_orders,
                    name="fetch-days-orders",
                ),
                path(
                    "checks-orders/<date>/<users>/print",
                    views.print_todays_orders,
                    name="print-todays-orders",
                ),
                path("shop-cart/", views.shop_cart, name="shop-cart"),
                path(
                    "view-order/<uuid:order_id>/<int:order_number>",
                    views.view_order,
                    name="view-order",
                ),
                path(
                    "view-order/<uuid:order_id>/<int:order_number>/print-pdf",
                    views.print_order_pdf,
                    name="print-order-pdf",
                ),
                path(
                    "sales-reports",
                    views.retrive_reports,
                    name="sales-reports",
                ),
                path(
                    "sales-reports/by_duration/",
                    views.retrive_reports_by_duration,
                    name="sales-reports-duration",
                ),
                path(
                    "sales-reports/by_dates/",
                    views.retrive_reports_by_dates,
                    name="sales-reports-dates",
                ),
                path(
                    "sales-reports/by_dates/print-pdf/<start_date>/<end_date>/<users>/",
                    views.retrive_reports_print,
                    name="print-reports",
                ),
            ]
        ),
    ),
]

myshopproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authapp.urls")),
    path("", include("core.urls")),
    path("sales/", include("sales.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import uuid
from django.db import models

# from django.contrib.auth import get_user_model
from django.conf import settings

# Create your models here.


class Product(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    name = models.CharField(max_length=255, unique=True)
    stock = models.PositiveIntegerField()
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    profit_rate = models.DecimalField(max_digits=3, decimal_places=2)
    slug = models.SlugField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()

    def __str__(self):
        return f"{self.name}"


class Order(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    code = models.CharField(max_length=6)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    customer_name = models.CharField(max_length=255, null=True, blank=True)
    overall_amount_paid = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()


class OrderItem(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty_bought = models.PositiveIntegerField()
    paid_amount = models.DecimalField(max_digits=6, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()

    def __str__(self):
        return f"{self.product},{self.qty_bought},{self.created:%d-%m-%y %H:%M}"

core/forms.py
from django import forms
from .models import Product

class ProductCreationForm(forms.ModelForm):
  class Meta:
    model = Product
    exclude = ('slug',)

core/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render

from django.conf import settings

from authapp.models import Account
from .models import Product, Order, OrderItem
from utils import generate_code, is_admin, render_attached_pdf
import io
from .tasks import import_products_task, remove_products_task
from celery.result import AsyncResult
from celery_progress.backend import Progress
import csv
from django.core.paginator import Paginator
from django.db.models import Q, Sum, F
from .forms import ProductCreationForm
import json
import datetime as dt
from django.utils import timezone
from django.db.models import QuerySet
from django_htmx.http import trigger_client_event
from django.views.decorators.http import require_POST


@login_required
@user_passes_test(is_admin)
def index(request):
    return render(request, "core/index.html")


@login_required
@user_passes_test(is_admin)
def products_home(request):
    products = Product.objects.all()
    context = {
        "products": products,
    }
    return render(request, "core/products/products.html", context)


@login_required
@user_passes_test(is_admin)
def load_products(request):
    limit = request.GET.get("l")
    page = request.GET.get("p")
    search_term = request.GET.get("s") if request.GET.get("s") is not None else ""

    if limit is not None:
        limit = int(limit)

    products = Product.objects.all().order_by("-created")
    if search_term != "":
        products = products.filter(Q(name__icontains=search_term)).order_by("-created")

    paginator = Paginator(object_list=products, per_page=limit)

    if page is None:
        page = 1

    page_obj = paginator.get_page(page)

    starting_number = 1
    stopping_number = limit

    if page_obj.has_previous():
        starting_number = page_obj.previous_page_number() * limit
        stopping_number = starting_number + limit

    pages = [
        {"number": page, "allow": type(page) == int}
        for page in list(page_obj.paginator.get_elided_page_range())  # type: ignore
    ]

    context = {
        "page_obj": page_obj,
        "number_of_products": len(products),
        "starting_number": starting_number,
        "stopping_number": stopping_number,
        "limit": limit,
        "search_term": search_term,
        "pages": pages,
    }
    return render(request, "core/partials/table_search.html", context)


@require_POST
@login_required
@user_passes_test(is_admin)
def update_product_stock(request, product_id):
    product = Product.objects.get(pk=product_id)
    stock = request.POST.get("stock")

    product.stock = stock
    product.save()
    context = {"product": product}
    return render(request, "core/partials/product_table_row.html", context)


@login_required
@user_passes_test(is_admin)
def import_products(request):
    context = {}
    return render(
        request,
        "core/products/import_products.html",
        context,
    )


@require_POST
@login_required
@user_passes_test(is_admin)
def do_import_products(request):
    if bool(request.FILES.get("file")):
        file = io.TextIOWrapper(request.FILES.get("file"))
        csv_reader = csv.DictReader(file)
        rows = [row for row in csv_reader if row.get("PRODUCT") != ""]

        import_task = import_products_task.delay(rows)  # type: ignore
        task_id = import_task.task_id
        progress = Progress(AsyncResult(task_id))
        info = progress.get_info()
        context = {
            "task_id": task_id,
            "info": info,
        }
        return render(request, "core/products/import_products_progress.html", context)
    else:
        context = {"error": "No file submitted"}

        return render(
            request,
            "core/products/import_products.html",
            context,
        )


@login_required
@user_passes_test(is_admin)
def track_import_progress(request, task_id):
    progress = Progress(AsyncResult(task_id))
    info = progress.get_info()

    context = {
        "task_id": task_id,
        "info": info,
    }
    response = render(request, "core/products/import_products_progress.html", context)
    if not info["complete"]:
        return response

    return trigger_client_event(response, "reload_products_table")


@login_required
@user_passes_test(is_admin)
def remove_all_products(request):
    context = {}
    return render(request, "core/products/remove_products_question.html", context)


@login_required
@user_passes_test(is_admin)
def track_remove_product_progress(request, task_id):
    progress = Progress(AsyncResult(task_id))
    info = progress.get_info()

    context = {
        "task_id": task_id,
        "info": info,
    }
    response = render(request, "core/products/remove_products_progress.html", context)
    if not info["complete"]:
        return response

    return trigger_client_event(response, "reload_products_table")


@login_required
@user_passes_test(is_admin)
def get_product_action_buttons(request):
    return render(request, "core/partials/product_action_buttons.html")


@login_required
@user_passes_test(is_admin)
def remove_all_products_question(request):
    context = {"ids": []}
    if request.method == "POST":
        context["ids"] = request.POST.getlist("ids")
    return render(request, "core/products/remove_all_products_question.html", context)


@login_required
@user_passes_test(is_admin)
def do_remove_products(request):
    ids = []
    if request.method == "POST":
        if request.POST.getlist("ids") is not None:
            ids = request.POST.getlist("ids")

    remove_task = remove_products_task.delay(ids)  # type: ignore
    task_id = remove_task.task_id
    progress = Progress(AsyncResult(task_id))
    info = progress.get_info()

    context = {
        "task_id": task_id,
        "info": info,
        "selected_removal": len(ids) > 0,
        "count": len(ids) if len(ids) > 0 else Product.objects.count(),
    }
    return render(request, "core/products/remove_products_progress.html", context)


@login_required
@user_passes_test(is_admin)
def add_product(request):
    form_title = "Enter new product details below"
    form = ProductCreationForm()
    if request.method == "POST":
        form = ProductCreationForm(request.POST)

        if form.is_valid():
            try:
                product = form.save(commit=False)

                if int(form.cleaned_data["cost"]) > 0:
                    product.profit_rate = abs(int(form.cleaned_data["cost"])) / abs(
                        int(form.cleaned_data["price"])
                    )
                else:
                    product.profit_rate = 0
                product.save()
            except Exception as e:
                print(e)
                context = {
                    "type": "danger",
                    "message": "New product could not be saved. Try again later.",
                }
                return render(request, "core/products/response.html", context)
            else:
                context = {
                    "type": "success",
                    "message": "New product successfully saved.",
                }
                response = render(request, "core/products/response.html", context)
                return trigger_client_event(response, "reload_products_table")

    context = {"form": form, "form_title": form_title}
    return render(request, "core/products/new_product.html", context)


@login_required
@user_passes_test(is_admin)
def update_product(request, product_id):
    form_title = "Update product details below"
    product = Product.objects.get(pk=product_id)
    form = ProductCreationForm(instance=product)
    if request.method == "POST":
        form = ProductCreationForm(request.POST, instance=product)
        if form.is_valid():
            try:
                product = form.save(commit=False)
                if int(form.cleaned_data["cost"]) > 0:
                    product.profit_rate = abs(int(form.cleaned_data["cost"])) / abs(
                        int(form.cleaned_data["price"])
                    )
                else:
                    product.profit_rate = 0
                product.save()
            except Exception as e:
                print(e)
                context = {
                    "type": "danger",
                    "message": "The product's update could not be saved. Try again later.",  # noqa: E501
                }
                return render(request, "core/products/response.html", context)
            else:
                context = {
                    "type": "success",
                    "message": "Product successfully updated.",
                }
                response = render(request, "core/products/response.html", context)
                return trigger_client_event(response, "reload_products_table")

    context = {"form": form, "form_title": form_title, "product": product}
    return render(request, "core/products/new_product.html", context)


@login_required
@user_passes_test(is_admin)
def remove_a_product_question(request, product_id):
    product = Product.objects.get(pk=product_id)
    context = {"product": product}
    return render(request, "core/products/remove_a_product_question.html", context)


@login_required
@user_passes_test(is_admin)
def do_remove_a_product(request, product_id):
    product = Product.objects.get(pk=product_id)
    product.delete()
    context = {
        "type": "success",
        "message": f"Product '{product}' successfully removed.",
        "product": product,
    }
    response = render(request, "core/products/response.html", context)
    return trigger_client_event(response, "reload_products_table")


@login_required
@user_passes_test(is_admin)
def orders(request):
    context = {}
    return render(request, "core/orders/orders.html", context)


@login_required
@user_passes_test(is_admin)

core/templates/core/products/import_products.html
<form method="post"
      hx-encoding="multipart/form-data"
      hx-post="{% url 'core:do-import-products' %}"
      hx-target="#new_products"
      hx-swap="innerHTML"
      x-data="{file: ''}">
  <div class="flex flex-col px-3 py-2 space-y-6 border-2 border-gray-600 rounded-md">
    <label class="block mb-2 text-xl font-medium text-gray-900 dark:text-white"
           for="file_input">Import new products</label>
    <div>
      <input class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400"
             aria-describedby="file_input_help"
             x-model="file"
             id="file_input"
             type="file"
             name="file"
             accept=".csv">
      <p class="mt-1 text-sm text-gray-500 dark:text-gray-300"
         id="file_input_help">Only .csv files are allowed.</p>
    </div>
    <div class="flex items-center justify-between">
      <button type="submit"
              :disabled="file === ''"
              class="inline-flex items-center text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center ">
        <svg width="18"
             height="18"
             viewBox="0 0 24 24"
             fill="none"
             stroke="#000"
             stroke-width="3"
             stroke-linecap="round">
        </svg>
        <span>Import now</span>
      </button>
      <button hx-get="{% url 'core:get-product-action-buttons' %}"
              hx-target="#new_products"
              hx-swap="innerHTML"
              class="text-white bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-gray-300 dark:focus:ring-gray-800 shadow-lg shadow-gray-500/50 dark:shadow-lg dark:shadow-gray-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
        Cancel
      </button>
    </div>
  </div>
</form>
<div class="flex items-center justify-between"></div>

core/templates/core/products/import_products_progress.html
<div class="flex flex-col space-y-6" {% if not info.complete %} hx-get="{% url 'core:import-products-status' task_id %}" hx-trigger="load delay:100ms" hx-target="this" {% endif %}>
  <h2 class="text-2xl  border-b-2 border-green-800 mb-2 px-2 py-1.5">
    Current Task: <span class="text-green-600 font-semibold">Importing new products</span>
  </h2>
  {% include "partials/progress_bar.html" %}
  {% if info.complete %}
    <button hx-get="{% url 'core:get-product-action-buttons' %}"
            hx-target="#new_products"
            hx-swap="innerHTML"
            class="text-white bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-gray-300 dark:focus:ring-gray-800 shadow-lg shadow-gray-500/50 dark:shadow-lg dark:shadow-gray-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
      Done
    </button>
  {% endif %}
</div>

core/templates/core/products/new_product.html
{% load widget_tweaks %}
<div class="w-full p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
  <form {% if product is not None %} hx-post="{% url 'core:update-product' product.id %}" {% else %} hx-post="{% url 'core:add-product' %}" {% endif %}
        hx-target="#new_products">
    <h2 class="pb-2 mb-3 font-semibold border-b-2 border-gray-600">{{ form_title }}</h2>
    <div class="flex flex-col mb-4 space-y-3">
      {% for field in form %}
        <div class="w-full">
          {{ field.label }}
          {{ field|add_class:"rounded-md border-2 w-full"|add_error_class:"border-red-600" }}
          {% for error in field.errors %}<span class="block text-xs text-red-400">{{ error }}</span>{% endfor %}
        </div>
      {% endfor %}
    </div>
    <div class="flex items-center justify-between">
      <button type="submit"
              class="text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center ">
        Submit
      </button>
      <button hx-get="{% url 'core:get-product-action-buttons' %}"
              hx-target="#new_products"
              hx-swap="innerHTML"
              class="text-white bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-gray-300 dark:focus:ring-gray-800 shadow-lg shadow-gray-500/50 dark:shadow-lg dark:shadow-gray-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
        Cancel
      </button>
    </div>
  </form>
</div>

core/templates/core/products/out_of_stock.html
<div class="flex flex-col space-y-4 border-2 border-gray-200 bg-gray-100 px-4 py-1.5 rounded-md">
  <div class="flex items-center justify-between pb-4">
    <div>
      <h2 class="text-xl font-semibold border-b-2 border-gray-800">Products Out of Stock</h2>
    </div>
    <label for="table-search" class="sr-only">Search</label>
    <div class="relative">
      <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
        <svg class="w-5 h-5 text-gray-500 dark:text-gray-400"
             aria-hidden="true"
             fill="currentColor"
             viewBox="0 0 20 20"
             xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd">
          </path>
        </svg>
      </div>
      <input type="text"
             id="table-search"
             name="s"
             hx-get="{% url 'core:load-out-of-stock' %}?p=1"
             hx-trigger="keyup changed delay:500ms"
             hx-target="#tbody"
             hx-swap="innerHTML"
             class="block p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-60 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
             placeholder="Search for items">
    </div>
  </div>
  <div class="relative shadow-md sm:rounded-lg">
    <table id="orders_products_table"
           class="w-full text-xs text-left text-gray-500 border-collapse table-fixed dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr class="flex">
          <th scope="col" class="flex-1 px-3 py-2 text-center">Product</th>
          <th scope="col" class="flex-1 px-3 py-2 text-center">Stock</th>
          <th scope="col" class="flex-1 px-3 py-2 text-center">Last Updated</th>
          <th scope="col" class="flex-1 px-3 py-2 text-center">Action</th>
        </tr>
      </thead>
      <tbody hx-target="this"
             hx-swap="innerHTML"
             hx-get="{% url 'core:load-orders-products' %}?p=1&s="
             hx-trigger="reload_products_with_stocks from:body"
             _="on keyup from #table-search remove <#orders_products_table>tbody>tr/>"
             class="overflow-y-auto block h-[450px]"
             id="tbody">
        {% include "core/products/out_of_stock_items.html" %}
      </tbody>
    </table>
  </div>
</div>

core/templates/core/products/out_of_stock_items.html
{% load humanize %}
{% for product in page_obj %}
  {% if forloop.last and page_obj.has_next %}
    <tr hx-get="{% url 'core:load-out-of-stock' %}?p={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}"
        hx-swap="afterend"
        hx-target="this"
        hx-trigger="intersect once"
        hx-vals="js:{ s: document.querySelector('#table-search').value }"
        class="flex items-center bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
    {% else %}
      <tr class="flex items-center bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
      {% endif %}
      <td class="flex-1 px-3 py-2 font-medium text-center text-gray-900 dark:text-white">{{ product }}</td>
      <td class="flex-1 px-3 py-2 text-center">{{ product.stock }}</td>
      <td class="flex-1 px-3 py-2 text-center">{{ product.updated|naturaltime }}</td>
      <td class="flex-1 px-3 py-2 text-center">
        {% comment %} <button type="button" type="button" class="text-[10px] text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full px-2 py-1 text-center mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-900">
          Update Stock
        </button> {% endcomment %}
        <button title="Update this product"
                hx-get="{% url 'core:update-product' product.id %}"
                hx-target="#new_products"
                class="flex items-center space-x-4 text-blue-400 hover:text-blue-600">
          <svg xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 24 24"
               stroke-width="1.5"
               stroke="currentColor"
               class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
          </svg>
          <span>Update</span>
        </button>
      </td>
    </tr>
  {% endfor %}

core/templates/core/products/remove_a_product_question.html
<div class="flex flex-col space-y-6 border-2 border-red-500 px-3 py-1.5 bg-red-50">
  <h2 class="text-sm font-semibold my-3 border-b-2 border-red-500">Removing Product: {{ product }}</h2>
  <h3 class="text-2xl font-light">This action is irreversible. Are you sure?</h3>
  <div class="flex space-x-6 p-2">
    <button hx-get="{% url 'core:do-remove-a-product' product.id %}"
            hx-target="#new_products"
            hx-swap="innerHTML"
            class="text-white bg-gradient-to-r from-red-500 via-red-600 to-red-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 shadow-lg shadow-red-500/50 dark:shadow-lg dark:shadow-red-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center ">
      Yes, Remove This Product
    </button>
    <button hx-get="{% url 'core:get-product-action-buttons' %}"
            hx-target="#new_products"
            hx-swap="innerHTML"
            class="text-white bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-gray-300 dark:focus:ring-gray-800 shadow-lg shadow-gray-500/50 dark:shadow-lg dark:shadow-gray-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
      Cancel
    </button>
  </div>
</div>

core/templates/core/products/remove_all_products_question.html
<div class="flex flex-col space-y-6 border-2 border-red-500 px-3 py-1.5 bg-red-50">
  <h2 class="text-sm font-semibold my-3 border-b-2 border-red-500">
    Removing
    {% if ids|length > 0 %}
      Selected
    {% else %}
      All
    {% endif %}
    Products
  </h2>
  <h3 class="text-2xl font-light">This action is irreversible. Are you sure?</h3>
  <div class="flex space-x-6 p-2">
    <button @click="selectAll = false;ids=[]" {% if ids|length > 0 %} hx-post="{% url 'core:do-remove-products' %}" hx-vals="js:{ ids: JSON.parse(document.querySelector('#product_ids').textContent) }" {% else %} hx-get="{% url 'core:do-remove-products' %}" {% endif %}
            hx-target="#new_products"
            hx-swap="innerHTML"
            class="text-white bg-gradient-to-r from-red-500 via-red-600 to-red-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 shadow-lg shadow-red-500/50 dark:shadow-lg dark:shadow-red-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center ">
      Yes, Remove
      {% if ids|length > 0 %}
        Selected
      {% else %}
        All
      {% endif %}
      Products
    </button>
    <button hx-get="{% url 'core:get-product-action-buttons' %}"
            hx-target="#new_products"
            hx-swap="innerHTML"
            class="text-white bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-gray-300 dark:focus:ring-gray-800 shadow-lg shadow-gray-500/50 dark:shadow-lg dark:shadow-gray-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
      No, Go Back
    </button>
  </div>
</div>
{{ ids|json_script:"product_ids" }}

core/templates/core/products/response.html
<div class="border-2 border-gray-800 px-4 py-2 rounded-md flex flex-col space-y-4">
  {% include "partials/alert_message.html" %}
  <div class="p-2">
    <button hx-get="{% url 'core:get-product-action-buttons' %}"
            hx-target="#new_products"
            hx-swap="innerHTML"
            class="text-white bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-gray-300 dark:focus:ring-gray-800 shadow-lg shadow-gray-500/50 dark:shadow-lg dark:shadow-gray-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
      Go Back
    </button>
  </div>
</div>