core/urls.py
from django.urls import include, path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="base"),
    path(
        "products/",
        include(
            [
                path("", views.products_home, name="products"),
                path("summary/", views.products_summary, name="products-summary"),
                path("load-products/", views.load_products, name="load-products"),
                path(
                    "<uuid:product_id>/update-stocks",
                    views.update_product_stock,
                    name="update-product-stock",
                ),
                path("import-products/", views.import_products, name="import-products"),
                path(
                    "import-products/do",
                    views.do_import_products,  # type: ignore
                    name="do-import-products",
                ),
                path(
                    "import-products/track_progress/<task_id>",
                    views.track_import_progress,
                    name="import-products-status",
                ),
                path(
                    "remove-products/",
                    views.remove_all_products,
                    name="remove-products",
                ),
                path(
                    "remove-products/question",
                    views.remove_all_products_question,
                    name="remove-products-question",
                ),
                path(
                    "remove-products/do",
                    views.do_remove_products,
                    name="do-remove-products",
                ),
                path(
                    "remove-products/track_progress/<task_id>",
                    views.track_remove_product_progress,
                    name="remove-products-status",
                ),
                path(
                    "get-product-action-buttons",
                    views.get_product_action_buttons,
                    name="get-product-action-buttons",
                ),
                path(
                    "add-product",
                    views.add_product,
                    name="add-product",
                ),
                path(
                    "<uuid:product_id>/update-product",
                    views.update_product,
                    name="update-product",
                ),
                path(
                    "<uuid:product_id>/remove-product",
                    views.remove_a_product_question,
                    name="remove-a-product-question",
                ),
                path(
                    "<uuid:product_id>/remove-product/do",
                    views.do_remove_a_product,
                    name="do-remove-a-product",
                ),
                path("out-of-stock/", views.out_of_stock, name="out-of-stock"),
                path(
                    "out-of-stock/load",
                    views.load_out_of_stock,
                    name="load-out-of-stock",
                ),
            ]
        ),
    ),
    path(
        "orders/",
        include(
            [
                path("", views.orders, name="orders"),
                path("sell-products/", views.orders_products, name="orders-products"),
                path(
                    "sell-products/load/",
                    views.load_orders_products,
                    name="load-orders-products",
                ),
                path("make-order/", views.make_order, name="make-order"),
                path("check-orders/", views.today_orders, name="today-orders"),
                path(
                    "check-orders/days",
                    views.fetch_days_orders,
                    name="fetch-days-orders",
                ),
                path(
                    "checks-orders/<date>/<users>/print",
                    views.print_todays_orders,
                    name="print-todays-orders",
                ),
                path("shop-cart/", views.shop_cart, name="shop-cart"),
                path(
                    "view-order/<uuid:order_id>/<int:order_number>",
                    views.view_order,
                    name="view-order",
                ),
                path(
                    "view-order/<uuid:order_id>/<int:order_number>/print-pdf",
                    views.print_order_pdf,
                    name="print-order-pdf",
                ),
                path(
                    "sales-reports",
                    views.retrive_reports,
                    name="sales-reports",
                ),
                path(
                    "sales-reports/by_duration/",
                    views.retrive_reports_by_duration,
                    name="sales-reports-duration",
                ),
                path(
                    "sales-reports/by_dates/",
                    views.retrive_reports_by_dates,
                    name="sales-reports-dates",
                ),
                path(
                    "sales-reports/by_dates/print-pdf/<start_date>/<end_date>/<users>/",
                    views.retrive_reports_print,
                    name="print-reports",
                ),
            ]
        ),
    ),
]

myshopproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authapp.urls")),
    path("", include("core.urls")),
    path("sales/", include("sales.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import uuid
from django.db import models

# from django.contrib.auth import get_user_model
from django.conf import settings

# Create your models here.


class Product(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    name = models.CharField(max_length=255, unique=True)
    stock = models.PositiveIntegerField()
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    profit_rate = models.DecimalField(max_digits=3, decimal_places=2)
    slug = models.SlugField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()

    def __str__(self):
        return f"{self.name}"


class Order(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    code = models.CharField(max_length=6)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    customer_name = models.CharField(max_length=255, null=True, blank=True)
    overall_amount_paid = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()


class OrderItem(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty_bought = models.PositiveIntegerField()
    paid_amount = models.DecimalField(max_digits=6, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()

    def __str__(self):
        return f"{self.product},{self.qty_bought},{self.created:%d-%m-%y %H:%M}"

core/forms.py
from django import forms
from .models import Product

class ProductCreationForm(forms.ModelForm):
  class Meta:
    model = Product
    exclude = ('slug',)

core/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render

from django.conf import settings

from authapp.models import Account
from .models import Product, Order, OrderItem
from utils import generate_code, is_admin, render_attached_pdf
import io
from .tasks import import_products_task, remove_products_task
from celery.result import AsyncResult
from celery_progress.backend import Progress
import csv
from django.core.paginator import Paginator
from django.db.models import Q, Sum, F
from .forms import ProductCreationForm
import json
import datetime as dt
from django.utils import timezone
from django.db.models import QuerySet
from django_htmx.http import trigger_client_event
from django.views.decorators.http import require_POST


@login_required
@user_passes_test(is_admin)
def index(request):
    return render(request, "core/index.html")


@login_required
@user_passes_test(is_admin)
def products_home(request):
    products = Product.objects.all()
    context = {
        "products": products,
    }
    return render(request, "core/products/products.html", context)


@login_required
@user_passes_test(is_admin)
def load_products(request):
    limit = request.GET.get("l")
    page = request.GET.get("p")
    search_term = request.GET.get("s") if request.GET.get("s") is not None else ""

    if limit is not None:
        limit = int(limit)

    products = Product.objects.all().order_by("-created")
    if search_term != "":
        products = products.filter(Q(name__icontains=search_term)).order_by("-created")

    paginator = Paginator(object_list=products, per_page=limit)

    if page is None:
        page = 1

    page_obj = paginator.get_page(page)

    starting_number = 1
    stopping_number = limit

    if page_obj.has_previous():
        starting_number = page_obj.previous_page_number() * limit
        stopping_number = starting_number + limit

    pages = [
        {"number": page, "allow": type(page) == int}
        for page in list(page_obj.paginator.get_elided_page_range())  # type: ignore
    ]

    context = {
        "page_obj": page_obj,
        "number_of_products": len(products),
        "starting_number": starting_number,
        "stopping_number": stopping_number,
        "limit": limit,
        "search_term": search_term,
        "pages": pages,
    }
    return render(request, "core/partials/table_search.html", context)


@require_POST
@login_required
@user_passes_test(is_admin)
def update_product_stock(request, product_id):
    product = Product.objects.get(pk=product_id)
    stock = request.POST.get("stock")

    product.stock = stock
    product.save()
    context = {"product": product}
    return render(request, "core/partials/product_table_row.html", context)


@login_required
@user_passes_test(is_admin)
def import_products(request):
    context = {}
    return render(
        request,
        "core/products/import_products.html",
        context,
    )


@require_POST
@login_required
@user_passes_test(is_admin)
def do_import_products(request):
    if bool(request.FILES.get("file")):
        file = io.TextIOWrapper(request.FILES.get("file"))
        csv_reader = csv.DictReader(file)
        rows = [row for row in csv_reader if row.get("PRODUCT") != ""]

        import_task = import_products_task.delay(rows)  # type: ignore
        task_id = import_task.task_id
        progress = Progress(AsyncResult(task_id))
        info = progress.get_info()
        context = {
            "task_id": task_id,
            "info": info,
        }
        return render(request, "core/products/import_products_progress.html", context)
    else:
        context = {"error": "No file submitted"}

        return render(
            request,
            "core/products/import_products.html",
            context,
        )


@login_required
@user_passes_test(is_admin)
def track_import_progress(request, task_id):
    progress = Progress(AsyncResult(task_id))
    info = progress.get_info()

    context = {
        "task_id": task_id,
        "info": info,
    }
    response = render(request, "core/products/import_products_progress.html", context)
    if not info["complete"]:
        return response

    return trigger_client_event(response, "reload_products_table")


@login_required
@user_passes_test(is_admin)
def remove_all_products(request):
    context = {}
    return render(request, "core/products/remove_products_question.html", context)


@login_required
@user_passes_test(is_admin)
def track_remove_product_progress(request, task_id):
    progress = Progress(AsyncResult(task_id))
    info = progress.get_info()

    context = {
        "task_id": task_id,
        "info": info,
    }
    response = render(request, "core/products/remove_products_progress.html", context)
    if not info["complete"]:
        return response

    return trigger_client_event(response, "reload_products_table")


@login_required
@user_passes_test(is_admin)
def get_product_action_buttons(request):
    return render(request, "core/partials/product_action_buttons.html")


@login_required
@user_passes_test(is_admin)
def remove_all_products_question(request):
    context = {"ids": []}
    if request.method == "POST":
        context["ids"] = request.POST.getlist("ids")
    return render(request, "core/products/remove_all_products_question.html", context)


@login_required
@user_passes_test(is_admin)
def do_remove_products(request):
    ids = []
    if request.method == "POST":
        if request.POST.getlist("ids") is not None:
            ids = request.POST.getlist("ids")

    remove_task = remove_products_task.delay(ids)  # type: ignore
    task_id = remove_task.task_id
    progress = Progress(AsyncResult(task_id))
    info = progress.get_info()

    context = {
        "task_id": task_id,
        "info": info,
        "selected_removal": len(ids) > 0,
        "count": len(ids) if len(ids) > 0 else Product.objects.count(),
    }
    return render(request, "core/products/remove_products_progress.html", context)


@login_required
@user_passes_test(is_admin)
def add_product(request):
    form_title = "Enter new product details below"
    form = ProductCreationForm()
    if request.method == "POST":
        form = ProductCreationForm(request.POST)

        if form.is_valid():
            try:
                product = form.save(commit=False)

                if int(form.cleaned_data["cost"]) > 0:
                    product.profit_rate = abs(int(form.cleaned_data["cost"])) / abs(
                        int(form.cleaned_data["price"])
                    )
                else:
                    product.profit_rate = 0
                product.save()
            except Exception as e:
                print(e)
                context = {
                    "type": "danger",
                    "message": "New product could not be saved. Try again later.",
                }
                return render(request, "core/products/response.html", context)
            else:
                context = {
                    "type": "success",
                    "message": "New product successfully saved.",
                }
                response = render(request, "core/products/response.html", context)
                return trigger_client_event(response, "reload_products_table")

    context = {"form": form, "form_title": form_title}
    return render(request, "core/products/new_product.html", context)


@login_required
@user_passes_test(is_admin)
def update_product(request, product_id):
    form_title = "Update product details below"
    product = Product.objects.get(pk=product_id)
    form = ProductCreationForm(instance=product)
    if request.method == "POST":
        form = ProductCreationForm(request.POST, instance=product)
        if form.is_valid():
            try:
                product = form.save(commit=False)
                if int(form.cleaned_data["cost"]) > 0:
                    product.profit_rate = abs(int(form.cleaned_data["cost"])) / abs(
                        int(form.cleaned_data["price"])
                    )
                else:
                    product.profit_rate = 0
                product.save()
            except Exception as e:
                print(e)
                context = {
                    "type": "danger",
                    "message": "The product's update could not be saved. Try again later.",  # noqa: E501
                }
                return render(request, "core/products/response.html", context)
            else:
                context = {
                    "type": "success",
                    "message": "Product successfully updated.",
                }
                response = render(request, "core/products/response.html", context)
                return trigger_client_event(response, "reload_products_table")

    context = {"form": form, "form_title": form_title, "product": product}
    return render(request, "core/products/new_product.html", context)


@login_required
@user_passes_test(is_admin)
def remove_a_product_question(request, product_id):
    product = Product.objects.get(pk=product_id)
    context = {"product": product}
    return render(request, "core/products/remove_a_product_question.html", context)


@login_required
@user_passes_test(is_admin)
def do_remove_a_product(request, product_id):
    product = Product.objects.get(pk=product_id)
    product.delete()
    context = {
        "type": "success",
        "message": f"Product '{product}' successfully removed.",
        "product": product,
    }
    response = render(request, "core/products/response.html", context)
    return trigger_client_event(response, "reload_products_table")


@login_required
@user_passes_test(is_admin)
def orders(request):
    context = {}
    return render(request, "core/orders/orders.html", context)


@login_required
@user_passes_test(is_admin)

core/templates/core/orders/all_orders.html
{% load humanize %}
<div class="flex flex-col col-span-2 px-3 py-2 space-y-2 border-2 border-gray-500 bg-gray-200/60">
    <h3 class="px-2 py-0.5 font-semibold border-b-2 border-gray-500">Orders &mdash; [{{ date }}]</h3>
        <table id="orders_products_table"
            class="w-full text-[10px] text-left text-gray-500 border-collapse table-fixed dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr class="flex">
                    <th scope="col" class="w-12 px-3 py-2 text-center">S/No.</th>
                    <th scope="col" class="w-24 px-3 py-2 text-center">Order Code</th>
                    <th scope="col" class="flex-1 px-3 py-2 text-center">Total Amount</th>
                    <th scope="col" class="flex-1 px-3 py-2 text-center">Time Created</th>
                </tr>
            </thead>
            <tbody class="overflow-y-auto block h-[350px]" id="tbody">
                {% for order in orders %}
                <tr
                    class="flex items-center bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                    <td class="w-12 px-3 py-2 font-medium text-center text-gray-900 dark:text-white">{{ forloop.counter }}</td>
                    <td class="w-24 px-3 py-2 font-medium text-center text-gray-900 dark:text-white">
                        <a class="text-blue-600 cursor-pointer hover:underline" hx-swap="innerHTML"
                            hx-target="#order_details"
                            hx-get="{% url 'core:view-order' order.id forloop.counter %}">{{ order.code }}</a>
                    </td>
                    <td class="flex-1 px-3 py-2 text-center">GHs {{ order.overall_amount_paid }}</td>
                    <td class="flex-1 px-3 py-2 text-center">{{ order.created|naturaltime }}</td>
                </tr>
                {% empty %}
                <tr class="flex items-center w-full">
                    <td class="flex-1 px-2 py-1 text-center"><span class="text-sm font-semibold text-red-600">NO ORDERS MADE BY {{  users }} ON THIS DATE {{ date }} </span></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    <div class="flex items-center justify-between w-full px-3 py-4 bg-green-200 border-2 border-green-300">
        <h3 class="font-semibold text-green-600">Total Sales: GHs {{ todays_total_orders|default:'0.00' }}</h3>
        {% if orders|length > 0 %}
        <div>
            <a href="{% url 'core:print-todays-orders' date users %}"
                class="text-[10px] text-white bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-gray-300 dark:focus:ring-gray-800 shadow-lg shadow-gray-500/50 dark:shadow-lg dark:shadow-gray-800/80 font-medium rounded-lg text-sm px-3 py-2 text-center mr-2 mb-2 ">
                Download Report
            </a>
        </div>
        {% endif %}
    </div>
</div>

core/templates/core/orders/order_details.html
{% load humanize %}
<div class="flex flex-col px-3 py-2 space-y-5 bg-green-200 border-2 border-green-300">
  <div class="flex items-center justify-between w-full">
    <h3 class="text-sm font-semibold border-b-2 border-gray-500">Order: <b>{{ order.code }}</b></h3>
    <h3 class="text-xs">Made By: <b>{{ order.user }}</b></h3>
  </div>
  <div>
    <table class="w-full text-xs text-left text-gray-500 border-collapse table-fixed dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr class="flex">
          <th scope="col" class="flex-1 px-3 py-2 text-center">Item Name</th>
          <th scope="col" class="flex-1 px-3 py-2 text-center">Qty Bought</th>
          <th scope="col" class="flex-1 px-3 py-2 text-center">Total Cost</th>
        </tr>
      </thead>
      <tbody class="overflow-y-auto block h-[350px]" id="tbody">
        {% for order_item in order.orderitem_set.all %}
          <tr class="flex items-center bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
            <td class="flex-1 px-3 py-2 font-medium text-center text-gray-900 dark:text-white">{{ order_item.product }}</td>
            <td class="flex-1 px-3 py-2 text-center">{{ order_item.qty_bought }}</td>
            <td class="flex-1 px-3 py-2 text-center">GHs{{ order_item.paid_amount }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="flex items-center justify-between w-full px-3 py-4 bg-green-200 border-2 border-green-300">
    <div class="flex flex-col space-y-1">
      <h4 class="text-sm font-light">
        Total Amount Paid:  <span class="font-semibold">GHs {{ order.overall_amount_paid }}</span>
      </h4>
      <span class="text-[10px] text-gray-600">Order Completed On: {{ order.created }}</span>
    </div>
    <div>
    <a href="{% url 'core:print-order-pdf' order.id order_number %}"
            class="text-[10px] text-white bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-gray-300 dark:focus:ring-gray-800 shadow-lg shadow-gray-500/50 dark:shadow-lg dark:shadow-gray-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
      Download Receipt
    </a>
  </div>
  </div>
</div>

core/templates/core/orders/order_made.html
<div class="flex flex-col px-4 py-2 space-y-4 border-2 border-gray-800 rounded-md">
  {% include "partials/alert_message.html" %}
  <div class="flex items-center p-2 space-x-6">
    <button @click="items=[]"
            hx-get="{% url 'core:shop-cart' %}"
            hx-target="#cart"
            hx-swap="innerHTML"
            class="text-white bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-gray-300 dark:focus:ring-gray-800 shadow-lg shadow-gray-500/50 dark:shadow-lg dark:shadow-gray-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
      Go to Cart
    </button>
    {% if order_number %}
      <a href="{% url 'core:print-order-pdf' order.id order_number %}"
         class="text-white bg-gradient-to-r from-fuchsia-500 via-fuchsia-600 to-fuchsia-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-fuchsia-300 dark:focus:ring-fuchsia-800 shadow-lg shadow-fuchsia-500/50 dark:shadow-lg dark:shadow-fuchsia-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
        Download Receipt
      </a>
    {% endif %}
  </div>
</div>

core/templates/core/orders/orders.html
{% extends "core/_core_base.html" %}
{% load humanize %}
{% block title %}
  Orders |
{% endblock title %}
{% block nav %}
  {% include "core/partials/nav.html" %}
{% endblock nav %}
{% block content %}
  <div>
    <div class="grid grid-cols-5 gap-y-16 gap-x-10 w-full h-full">
      <div class="col-span-4"
           id="results"
           hx-trigger="load, reload_summary"
           hx-target="this"
           hx-get="{% url 'core:sales-reports' %}"></div>
      <div class="flex flex-col space-y-6 py-6 " id="orders_links">{% include "core/orders/orders_buttons.html" %}</div>
    </div>
  </div>
{% endblock content %}

core/templates/core/orders/orders_buttons.html
<button hx-swap="innerHTML"
        hx-target="#results"
        hx-get="{% url 'core:sales-reports' %}"
        class="text-white bg-gradient-to-r from-red-500 via-red-600 to-red-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 shadow-lg shadow-red-500/50 dark:shadow-lg dark:shadow-red-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
  Sales Reports
</button>
<button type="button"
        hx-get="{% url 'core:orders-products' %}"
        hx-swap="innerHTML"
        hx-target="#results"
        class="text-white bg-gradient-to-r from-green-500 via-green-600 to-green-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-green-300 dark:focus:ring-green-800 shadow-lg shadow-green-500/50 dark:shadow-lg dark:shadow-green-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
  Make an order
</button>
<button type="button"
        hx-swap="innerHTML"
        hx-target="#results"
        hx-get="{% url 'core:today-orders' %}"
        class="text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800 shadow-lg shadow-purple-500/50 dark:shadow-lg dark:shadow-purple-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
    All Orders
</button>

core/templates/core/orders/out_of_stock.html
<div class="grid grid-cols-3 gap-x-8 gap-y-6">
<div class="col-span-2 flex flex-col space-y-4 border-2 border-gray-200 bg-gray-100 px-4 py-1.5 rounded-md">

  <div class="flex items-center justify-between pb-4">
    <div>
      <h2 class="font-semibold text-xl border-b-2 border-gray-800">Products Out of Stock</h2>
    </div>
    <label for="table-search" class="sr-only">Search</label>
    <div class="relative">
      <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
        <svg class="w-5 h-5 text-gray-500 dark:text-gray-400"
             aria-hidden="true"
             fill="currentColor"
             viewBox="0 0 20 20"
             xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd">
          </path>
        </svg>
      </div>
      <input type="text"
             id="table-search"
             name="s"
             hx-get="{% url 'core:load-out-of-stock' %}?p=1"
             hx-trigger="keyup changed delay:500ms"
             hx-target="#tbody"
             hx-swap="beforeend"
             class="block p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-60 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
             placeholder="Search for items">
    </div>
  </div>
  <div class="relative shadow-md sm:rounded-lg" >
    <table id="orders_products_table" class="table-fixed border-collapse w-full text-xs text-left text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr class="flex">
          <th scope="col" class="text-center flex-1 px-3 py-2">Product</th>
          <th scope="col" class="text-center flex-1 px-3 py-2">Stock</th>
          <th scope="col" class="text-center flex-1 px-3 py-2">Last Updated</th>
          <th scope="col" class="text-center flex-1 px-3 py-2">Action</th>
        </tr>
      </thead>
      <tbody hx-target="this" hx-swap="innerHTML" hx-get="{% url 'core:load-orders-products' %}?p=1&s=" hx-trigger="reload_products_with_stocks from:body" _="on keyup from #table-search remove <#orders_products_table>tbody>tr/>" class="overflow-y-auto block h-[450px]" id="tbody">
        {% include "core/orders/out_of_stock_items.html" %}
      </tbody>
    </table>
  </div>
</div>
<div id="update_stock_form" class="border-2 border-gray-100 bg-gray-50 px-4 py-2 rounded-md"></div>
</div>

core/templates/core/orders/products_with_stocks_table_rows.html
{% for product in page_obj %}
  {% if forloop.last and page_obj.has_next %}
    <tr hx-get="{% url 'core:load-orders-products' %}?p={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}"
        hx-swap="afterend"
        hx-target="this"
        hx-trigger="intersect once"
        hx-vals="js:{ s: document.querySelector('#table-search').value }"
        x-data="{id: '{{ product.id }}', name: '{{ product.name }}', stock: {{ product.stock }}, price: {{ product.price }} }"
        class="flex items-center bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
    {% else %}
      <tr x-data="{id: '{{ product.id }}', name: '{{ product.name }}', stock: {{ product.stock }}, price: {{ product.price }} }"
          class="flex items-center bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
      {% endif %}
      <td class="text-center flex-1 px-3 py-2 font-medium text-gray-900 dark:text-white"
          x-text="name"></td>
      <td class="text-center flex-1 px-3 py-2" x-text="stock"></td>
      <td class="text-center flex-1 px-3 py-2 text-gray-900 dark:text-white"
          x-text="price"></td>
      <td class="text-center flex-1 px-3 py-2">
        <button type="button"
                @click="() => add_to_card(id, name, stock, price)"
                type="button"
                class="text-[10px] text-white bg-red-700 hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300 font-medium rounded-full px-2 py-1 text-center mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">
          Add to Cart
        </button>
      </td>
    </tr>
  {% endfor %}