core/urls.py
from django.urls import include, path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="base"),
    path(
        "products/",
        include(
            [
                path("", views.products_home, name="products"),
                path("summary/", views.products_summary, name="products-summary"),
                path("load-products/", views.load_products, name="load-products"),
                path(
                    "<uuid:product_id>/update-stocks",
                    views.update_product_stock,
                    name="update-product-stock",
                ),
                path("import-products/", views.import_products, name="import-products"),
                path(
                    "import-products/do",
                    views.do_import_products,  # type: ignore
                    name="do-import-products",
                ),
                path(
                    "import-products/track_progress/<task_id>",
                    views.track_import_progress,
                    name="import-products-status",
                ),
                path(
                    "remove-products/",
                    views.remove_all_products,
                    name="remove-products",
                ),
                path(
                    "remove-products/question",
                    views.remove_all_products_question,
                    name="remove-products-question",
                ),
                path(
                    "remove-products/do",
                    views.do_remove_products,
                    name="do-remove-products",
                ),
                path(
                    "remove-products/track_progress/<task_id>",
                    views.track_remove_product_progress,
                    name="remove-products-status",
                ),
                path(
                    "get-product-action-buttons",
                    views.get_product_action_buttons,
                    name="get-product-action-buttons",
                ),
                path(
                    "add-product",
                    views.add_product,
                    name="add-product",
                ),
                path(
                    "<uuid:product_id>/update-product",
                    views.update_product,
                    name="update-product",
                ),
                path(
                    "<uuid:product_id>/remove-product",
                    views.remove_a_product_question,
                    name="remove-a-product-question",
                ),
                path(
                    "<uuid:product_id>/remove-product/do",
                    views.do_remove_a_product,
                    name="do-remove-a-product",
                ),
                path("out-of-stock/", views.out_of_stock, name="out-of-stock"),
                path(
                    "out-of-stock/load",
                    views.load_out_of_stock,
                    name="load-out-of-stock",
                ),
            ]
        ),
    ),
    path(
        "orders/",
        include(
            [
                path("", views.orders, name="orders"),
                path("sell-products/", views.orders_products, name="orders-products"),
                path(
                    "sell-products/load/",
                    views.load_orders_products,
                    name="load-orders-products",
                ),
                path("make-order/", views.make_order, name="make-order"),
                path("check-orders/", views.today_orders, name="today-orders"),
                path(
                    "check-orders/days",
                    views.fetch_days_orders,
                    name="fetch-days-orders",
                ),
                path(
                    "checks-orders/<date>/<users>/print",
                    views.print_todays_orders,
                    name="print-todays-orders",
                ),
                path("shop-cart/", views.shop_cart, name="shop-cart"),
                path(
                    "view-order/<uuid:order_id>/<int:order_number>",
                    views.view_order,
                    name="view-order",
                ),
                path(
                    "view-order/<uuid:order_id>/<int:order_number>/print-pdf",
                    views.print_order_pdf,
                    name="print-order-pdf",
                ),
                path(
                    "sales-reports",
                    views.retrive_reports,
                    name="sales-reports",
                ),
                path(
                    "sales-reports/by_duration/",
                    views.retrive_reports_by_duration,
                    name="sales-reports-duration",
                ),
                path(
                    "sales-reports/by_dates/",
                    views.retrive_reports_by_dates,
                    name="sales-reports-dates",
                ),
                path(
                    "sales-reports/by_dates/print-pdf/<start_date>/<end_date>/<users>/",
                    views.retrive_reports_print,
                    name="print-reports",
                ),
            ]
        ),
    ),
]

myshopproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authapp.urls")),
    path("", include("core.urls")),
    path("sales/", include("sales.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import include, path
from . import views

app_name = "sales"

urlpatterns = [
    path(
        "",
        include(
            [
                path("", views.index, name="base"),
                path("sell-products/", views.orders_products, name="orders-products"),
                path(
                    "sell-products/load/",
                    views.load_orders_products,
                    name="load-orders-products",
                ),
                path("make-order/", views.make_order, name="make-order"),
                path("today-orders/", views.today_orders, name="today-orders"),
                path(
                    "today-orders/print",
                    views.print_todays_orders,
                    name="print-todays-orders",
                ),
                path("shop-cart/", views.shop_cart, name="shop-cart"),
                path(
                    "view-order/<uuid:order_id>/<int:order_number>",
                    views.view_order,
                    name="view-order",
                ),
                path(
                    "view-order/<uuid:order_id>/<int:order_number>/print-pdf",
                    views.print_order_pdf,
                    name="print-order-pdf",
                ),
            ]
        ),
    )
]

core/models.py
import uuid
from django.db import models

# from django.contrib.auth import get_user_model
from django.conf import settings

# Create your models here.


class Product(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    name = models.CharField(max_length=255, unique=True)
    stock = models.PositiveIntegerField()
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    profit_rate = models.DecimalField(max_digits=3, decimal_places=2)
    slug = models.SlugField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()

    def __str__(self):
        return f"{self.name}"


class Order(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    code = models.CharField(max_length=6)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    customer_name = models.CharField(max_length=255, null=True, blank=True)
    overall_amount_paid = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()


class OrderItem(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty_bought = models.PositiveIntegerField()
    paid_amount = models.DecimalField(max_digits=6, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()

    def __str__(self):
        return f"{self.product},{self.qty_bought},{self.created:%d-%m-%y %H:%M}"

sales/models.py
from django.db import models

# Create your models here.

sales/templates/sales/orders/cart_table.html
<div class="flex flex-col h-full space-y-4 ">
  <div class="flex items-center justify-between w-full h-12 px-4 py-1 bg-green-400/10">
    <h2 class="text-xl font-semibold">Cart</h2>
    <button @click="items=[]"
            class="text-xs text-white rounded-md px-2 py-0.5 bg-gradient-to-br from-red-400 via-red-500 to-red-600 hover:from-red-600 hover:to-red-400 ">
      Clear Cart
    </button>
  </div>
  <div class="flex flex-col justify-between h-full">
    <table class="w-full text-xs text-left text-gray-500 border-collapse table-fixed dark:text-gray-400">
      <thead class="h-8 text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr class="flex text-center">
          <th scope="col" class="w-32 px-3 py-2">Product</th>
          <th scope="col" class="flex-1 px-3 py-2">Qty</th>
          <th scope="col" class="flex-1 px-3 py-2">Price</th>
          <th scope="col" class="flex-1 px-3 py-2">Total Price</th>
          <th scope="col" class="flex-1 w-12 px-3 py-2"></th>
        </tr>
      </thead>
      <tbody class="block overflow-y-auto h-[360px] xl:h-[380px] 2xl:h-[400px] text-[10px]">
        <template x-for="item in items" x-cloak x-show="items.length > 0">
          <tr class="flex items-center bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
            <td class="w-32 px-3 py-2 font-semibold text-gray-900 dark:text-white"
                x-text="item.name"></td>
            <td class="flex items-center flex-1 space-x-1">
              <button @click="item.qty = subtract(item.qty, item.stock)"
                      class="inline-flex items-center p-1 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-full focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"
                      type="button">
                <span class="sr-only">Quantity button</span>
                <svg class="w-3 h-3"
                     aria-hidden="true"
                     fill="currentColor"
                     viewBox="0 0 20 20"
                     xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path>
                </svg>
              </button>
              <div>
                <input x-model="item.qty"
                       type="number"
                       id="first_product"
                       class="bg-gray-50 w-14 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block px-2.5 py-1 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                       placeholder="1"
                       :min="1"
                       :max="item.stock"
                       required>
              </div>
              <button @click="item.qty = add(item.qty, item.stock)"
                      class="inline-flex items-center p-1 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-full focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"
                      type="button">
                <span class="sr-only">Quantity button</span>
                <svg class="w-3 h-3"
                     aria-hidden="true"
                     fill="currentColor"
                     viewBox="0 0 20 20"
                     xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd">
                  </path>
                </svg>
              </button>
            </td>
            <td class="flex-1 px-3 py-2 text-gray-900 dark:text-white"
                x-text="item.price"></td>
            <td class="flex-1 px-3 py-2 text-gray-900 dark:text-white"
                x-text="calcTotalPrice(item)"></td>
            <td class="flex-1 text-center">
              <button title="Remove this item from the cart"
                      @click="items = items.filter(t => t.id != item.id)"
                      class="w-4 text-red-400 hover:text-red-600">
                <svg class="w-4 h-4"
                     aria-hidden="true"
                     fill="currentColor"
                     viewBox="0 0 20 20"
                     stroke="currentColor"
                     stroke-width="1.5"
                     xmlns="http://www.w3.org/2000/svg">
                  <path d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" stroke-linecap="round" stroke-linejoin="round">
                  </path>
                </svg>
              </button>
            </td>
          </tr>
        </template>
        <tr x-cloak
            x-show="items.length === 0"
            class="flex w-full text-center bg-white/50">
          <td class="flex-1 px-4 py-2 text-xl font-medium text-center text-red-500">Cart is empty</td>
        </tr>
      </tbody>
    </table>
    <div class="flex items-center justify-between">
      <div class="flex items-center px-4 py-1 space-x-4 text-white bg-gray-800 ">
        <h2 class="text-[10px] font-semibold">Total Cost</h2>
        <span class="text-xl font-semibold" x-text="totalPayment()"></span>
      </div>
      {% url 'sales:make-order' as order_now %}
      <button :disabled="items.length === 0"
              @click="() => { if (items.length === 0) { window.alert('Cart is empty') } else { htmx.ajax('POST','{{ order_now }}', {target: '#cart', swap:'innerHTML', values: { items: items }}) }}"
              class="text-white bg-gradient-to-r from-green-500 via-green-600 to-green-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">
        Accept Payment
      </button>
    </div>
  </div>
</div>

sales/templates/sales/orders/order_details.html
{% load humanize %}
<div class="flex flex-col px-3 py-2 space-y-5 bg-green-200 border-2 border-green-300">
  <div>
    <h3 class="text-sm font-semibold border-b-2 border-gray-500">Order {{ order_number }} Receipt</h3>
  </div>
  <div>
    <table class="w-full text-xs text-left text-gray-500 border-collapse table-fixed dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr class="flex">
          <th scope="col" class="flex-1 px-3 py-2 text-center">Item Name</th>
          <th scope="col" class="flex-1 px-3 py-2 text-center">Qty Bought</th>
          <th scope="col" class="flex-1 px-3 py-2 text-center">Total Cost</th>
        </tr>
      </thead>
      <tbody class="overflow-y-auto block h-[400px]" id="tbody">
        {% for order_item in order.orderitem_set.all %}
          <tr class="flex items-center bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
            <td class="flex-1 px-3 py-2 font-medium text-center text-gray-900 dark:text-white">{{ order_item.product }}</td>
            <td class="flex-1 px-3 py-2 text-center">{{ order_item.qty_bought }}</td>
            <td class="flex-1 px-3 py-2 text-center">GHs{{ order_item.paid_amount }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="flex justify-between px-3 py-2 space-y-2 text-white bg-gray-900">
    <div class="flex flex-col space-y-1">
      <h4 class="text-sm font-light">
        Total Amount Paid:  <span class="font-semibold">GHs {{ order.overall_amount_paid }}</span>
      </h4>
      <span class="text-[10px] text-gray-600">Order Completed On: {{ order.created }}</span>
    </div>
    <a href="{% url 'sales:print-order-pdf' order.id order_number %}"
            class="text-white bg-gradient-to-r from-fuchsia-500 via-fuchsia-600 to-fuchsia-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-fuchsia-300 dark:focus:ring-fuchsia-800 shadow-lg shadow-fuchsia-500/50 dark:shadow-lg dark:shadow-fuchsia-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
      Download Receipt
    </a>
  </div>
</div>

sales/templates/sales/orders/order_made.html
<div class="flex flex-col px-4 py-2 space-y-4 border-2 border-gray-800 rounded-md">
  {% include "partials/alert_message.html" %}
  <div class="flex items-center p-2 space-x-6">
    <button @click="items=[]"
            hx-get="{% url 'sales:shop-cart' %}"
            hx-target="#cart"
            hx-swap="innerHTML"
            class="text-white bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-gray-300 dark:focus:ring-gray-800 shadow-lg shadow-gray-500/50 dark:shadow-lg dark:shadow-gray-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
      Go to Cart
    </button>
    {% if order_number %}
      <a href="{% url 'sales:print-order-pdf' order.id order_number %}"
         class="text-white bg-gradient-to-r from-fuchsia-500 via-fuchsia-600 to-fuchsia-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-fuchsia-300 dark:focus:ring-fuchsia-800 shadow-lg shadow-fuchsia-500/50 dark:shadow-lg dark:shadow-fuchsia-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
        Download Receipt
      </a>
    {% endif %}
  </div>
</div>

sales/templates/sales/orders/orders_buttons.html
<button type="button"
        hx-get="{% url 'sales:orders-products' %}"
        hx-swap="innerHTML"
        hx-target="#results"
        class="text-white bg-gradient-to-r from-orange-500 via-orange-600 to-orange-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-orange-300 dark:focus:ring-orange-800 shadow-lg shadow-orange-500/50 dark:shadow-lg dark:shadow-orange-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
  Make an order
</button>
<button type="button"
        hx-swap="innerHTML"
        hx-target="#results"
        hx-get="{% url 'sales:today-orders' %}"
        class="text-white bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800 shadow-lg shadow-purple-500/50 dark:shadow-lg dark:shadow-purple-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
  My Orders
</button>

sales/templates/sales/orders/products_for_sale_table.html
<div class="grid grid-cols-4 gap-x-10"
     x-data="{items: [], calcTotalPrice(item) { item.total_price= parseFloat(item.price * item.qty).toFixed(2); return item.total_price;}, totalPayment() { let amnts = this.items.map(item => parseFloat(item.total_price));return amnts.reduce((a, c)=> a + c, 0).toFixed(2)}, add_to_card(id, name, stock, price) { if (this.items.findIndex(i => i.id === id) === -1) this.items.push({id, name, stock, qty:1, price})}}">
  <div class="col-span-2">
    <div class="flex items-center justify-between pb-4">
      <div>
        <h2 class="text-xl font-semibold border-b-2 border-gray-800">All Products</h2>
      </div>
      <label for="table-search" class="sr-only">Search</label>
      <div class="relative">
        <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
          <svg class="w-5 h-5 text-gray-500 dark:text-gray-400"
               aria-hidden="true"
               fill="currentColor"
               viewBox="0 0 20 20"
               xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd">
            </path>
          </svg>
        </div>
        <input type="text"
               id="table-search"
               name="s"
               hx-get="{% url 'sales:load-orders-products' %}?p=1"
               hx-trigger="keyup changed delay:500ms"
               hx-target="#tbody"
               hx-swap="innerHTML"
               hx-ext="debug"
               class="block p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-60 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
               placeholder="Search for items">
      </div>
    </div>
    <div class="relative shadow-md sm:rounded-lg">
      <table id="orders_products_table"
             class="flex flex-col w-full text-xs text-left text-gray-500 border-collapse table-fixed dark:text-gray-400">
        <thead class="h-8 text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr class="flex">
            <th scope="col" class="flex-1 px-3 py-2 text-center">Product</th>
            <th scope="col" class="flex-1 px-3 py-2 text-center">In Stock</th>
            <th scope="col" class="flex-1 px-3 py-2 text-center">Price</th>
            <th scope="col" class="flex-1 px-3 py-2 text-center">Action</th>
          </tr>
        </thead>
        <tbody hx-target="this"
               hx-swap="innerHTML"
               hx-get="{% url 'sales:load-orders-products' %}?p=1&s="
               hx-trigger="reload_products_with_stocks from:body"
               _="on keyup from #table-search remove <#orders_products_table>tbody>tr/>"
               class="block overflow-y-auto h-[400px] md:h-[440px] lg:h-[460px] xl:h-[480px] 2xl:h-[500px]"
               id="tbody">
          {% include "sales/orders/products_with_stocks_table_rows.html" %}
        </tbody>
      </table>
    </div>
  </div>
  <div id="cart" class="col-span-2 p-4 pb-0 bg-green-100">{% include "sales/orders/cart_table.html" %}</div>
</div>
<script>
  function subtract(qty, stock) { 
    if (qty > 1 ) { 
      return qty - 1
    } else {
      return 1;
    }
  }

  function add(qty, stock) { 
    let next_qty = qty + 1;
    if (next_qty <= stock) return next_qty; 
    return stock;
  }


</script>

sales/templates/sales/orders/products_with_stocks_table_rows.html
{% for product in page_obj %}
  {% if forloop.last and page_obj.has_next %}
    <tr hx-get="{% url 'sales:load-orders-products' %}?p={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}"
        hx-swap="afterend"
        hx-target="this"
        hx-trigger="intersect once"
        hx-vals="js:{ s: document.querySelector('#table-search').value }"
        x-data="{id: '{{ product.id }}', name: '{{ product.name }}', stock: {{ product.stock }}, price: {{ product.price }} }"
        class="text-[10px] flex items-center bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
    {% else %}
      <tr x-data="{id: '{{ product.id }}', name: '{{ product.name }}', stock: {{ product.stock }}, price: {{ product.price }} }"
          class="flex items-center bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
      {% endif %}
      <td class="flex-1 px-3 py-2 font-medium text-center text-gray-900 dark:text-white"
          x-text="name"></td>
      <td class="flex-1 px-3 py-2 text-center" x-text="stock"></td>
      <td class="flex-1 px-3 py-2 text-center text-gray-900 dark:text-white"
          x-text="price"></td>
      <td class="flex-1 px-3 py-2 text-center">
        <button type="button"
                @click="() => add_to_card(id, name, stock, price)"
                type="button"
                class="text-[8px] px-2 py-1 mb-2 font-medium text-center text-white bg-red-700 rounded-full hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">
          Add to Cart
        </button>
      </td>
    </tr>
  {% endfor %}

sales/templates/sales/orders/todays_orders.html
{% load humanize %}
<div class="grid w-full grid-cols-4 gap-x-8 gap-y-6">
  <div class="flex flex-col col-span-2 space-y-5">
    <h3 class="font-semibold border-b-2 border-gray-500">Today's Orders</h3>
    <div>
      <table id="orders_products_table"
             class="w-full text-xs text-left text-gray-500 border-collapse table-fixed dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr class="flex">
            <th scope="col" class="flex-1 px-3 py-2 text-center">Order No.</th>
            <th scope="col" class="flex-1 px-3 py-2 text-center">Total Amount</th>
            <th scope="col" class="flex-1 px-3 py-2 text-center">Time Created</th>
          </tr>
        </thead>
        <tbody class="overflow-y-auto block h-[420px]" id="tbody">
          {% for order in orders %}
            <tr class="flex items-center bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
              <td class="flex-1 px-3 py-2 font-medium text-center text-gray-900 dark:text-white">
                <a class="text-blue-600 cursor-pointer hover:underline"
                   hx-swap="innerHTML"
                   hx-target="#order_details"
                   hx-get="{% url 'sales:view-order' order.id forloop.counter %}">Order {{ forloop.counter }}</a>
              </td>
              <td class="flex-1 px-3 py-2 text-center">GHs {{ order.overall_amount_paid }}</td>
              <td class="flex-1 px-3 py-2 text-center">{{ order.created|naturaltime }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="flex items-center justify-between px-2 py-1 bg-green-200 border-2 border-green-300">
      <h3 class="font-semibold text-green-600">Total Sales: GHs {{ todays_total_orders }}</h3>
      <a href="{% url 'sales:print-todays-orders' %}"
         class="text-white bg-gradient-to-r from-fuchsia-500 via-fuchsia-600 to-fuchsia-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-fuchsia-300 dark:focus:ring-fuchsia-800 shadow-lg shadow-fuchsia-500/50 dark:shadow-lg dark:shadow-fuchsia-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
        Download Today's Sales
      </a>
    </div>
  </div>
  <div id="order_details" class="col-span-2"></div>
</div>