authapp/urls.py
from django.urls import path
from . import views

app_name = 'auth'
urlpatterns = [
    path('login/', views.signin, name="login"),
    path('login_success/', views.login_success, name="login_success"),
    path('logout', views.signout, name="logout"),
]

core/urls.py
from django.urls import include, path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="base"),
    path(
        "products/",
        include(
            [
                path("", views.products_home, name="products"),
                path("summary/", views.products_summary, name="products-summary"),
                path("load-products/", views.load_products, name="load-products"),
                path(
                    "<uuid:product_id>/update-stocks",
                    views.update_product_stock,
                    name="update-product-stock",
                ),
                path("import-products/", views.import_products, name="import-products"),
                path(
                    "import-products/do",
                    views.do_import_products,  # type: ignore
                    name="do-import-products",
                ),
                path(
                    "import-products/track_progress/<task_id>",
                    views.track_import_progress,
                    name="import-products-status",
                ),
                path(
                    "remove-products/",
                    views.remove_all_products,
                    name="remove-products",
                ),
                path(
                    "remove-products/question",
                    views.remove_all_products_question,
                    name="remove-products-question",
                ),
                path(
                    "remove-products/do",
                    views.do_remove_products,
                    name="do-remove-products",
                ),
                path(
                    "remove-products/track_progress/<task_id>",
                    views.track_remove_product_progress,
                    name="remove-products-status",
                ),
                path(
                    "get-product-action-buttons",
                    views.get_product_action_buttons,
                    name="get-product-action-buttons",
                ),
                path(
                    "add-product",
                    views.add_product,
                    name="add-product",
                ),
                path(
                    "<uuid:product_id>/update-product",
                    views.update_product,
                    name="update-product",
                ),
                path(
                    "<uuid:product_id>/remove-product",
                    views.remove_a_product_question,
                    name="remove-a-product-question",
                ),
                path(
                    "<uuid:product_id>/remove-product/do",
                    views.do_remove_a_product,
                    name="do-remove-a-product",
                ),
                path("out-of-stock/", views.out_of_stock, name="out-of-stock"),
                path(
                    "out-of-stock/load",
                    views.load_out_of_stock,
                    name="load-out-of-stock",
                ),
            ]
        ),
    ),
    path(
        "orders/",
        include(
            [
                path("", views.orders, name="orders"),
                path("sell-products/", views.orders_products, name="orders-products"),
                path(
                    "sell-products/load/",
                    views.load_orders_products,
                    name="load-orders-products",
                ),
                path("make-order/", views.make_order, name="make-order"),
                path("check-orders/", views.today_orders, name="today-orders"),
                path(
                    "check-orders/days",
                    views.fetch_days_orders,
                    name="fetch-days-orders",
                ),
                path(
                    "checks-orders/<date>/<users>/print",
                    views.print_todays_orders,
                    name="print-todays-orders",
                ),
                path("shop-cart/", views.shop_cart, name="shop-cart"),
                path(
                    "view-order/<uuid:order_id>/<int:order_number>",
                    views.view_order,
                    name="view-order",
                ),
                path(
                    "view-order/<uuid:order_id>/<int:order_number>/print-pdf",
                    views.print_order_pdf,
                    name="print-order-pdf",
                ),
                path(
                    "sales-reports",
                    views.retrive_reports,
                    name="sales-reports",
                ),
                path(
                    "sales-reports/by_duration/",
                    views.retrive_reports_by_duration,
                    name="sales-reports-duration",
                ),
                path(
                    "sales-reports/by_dates/",
                    views.retrive_reports_by_dates,
                    name="sales-reports-dates",
                ),
                path(
                    "sales-reports/by_dates/print-pdf/<start_date>/<end_date>/<users>/",
                    views.retrive_reports_print,
                    name="print-reports",
                ),
            ]
        ),
    ),
]

myshopproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authapp.urls")),
    path("", include("core.urls")),
    path("sales/", include("sales.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from .models import Product

class ProductCreationForm(forms.ModelForm):
  class Meta:
    model = Product
    exclude = ('slug',)

core/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render

from django.conf import settings

from authapp.models import Account
from .models import Product, Order, OrderItem
from utils import generate_code, is_admin, render_attached_pdf
import io
from .tasks import import_products_task, remove_products_task
from celery.result import AsyncResult
from celery_progress.backend import Progress
import csv
from django.core.paginator import Paginator
from django.db.models import Q, Sum, F
from .forms import ProductCreationForm
import json
import datetime as dt
from django.utils import timezone
from django.db.models import QuerySet
from django_htmx.http import trigger_client_event
from django.views.decorators.http import require_POST


@login_required
@user_passes_test(is_admin)
def index(request):
    return render(request, "core/index.html")


@login_required
@user_passes_test(is_admin)
def products_home(request):
    products = Product.objects.all()
    context = {
        "products": products,
    }
    return render(request, "core/products/products.html", context)


@login_required
@user_passes_test(is_admin)
def load_products(request):
    limit = request.GET.get("l")
    page = request.GET.get("p")
    search_term = request.GET.get("s") if request.GET.get("s") is not None else ""

    if limit is not None:
        limit = int(limit)

    products = Product.objects.all().order_by("-created")
    if search_term != "":
        products = products.filter(Q(name__icontains=search_term)).order_by("-created")

    paginator = Paginator(object_list=products, per_page=limit)

    if page is None:
        page = 1

    page_obj = paginator.get_page(page)

    starting_number = 1
    stopping_number = limit

    if page_obj.has_previous():
        starting_number = page_obj.previous_page_number() * limit
        stopping_number = starting_number + limit

    pages = [
        {"number": page, "allow": type(page) == int}
        for page in list(page_obj.paginator.get_elided_page_range())  # type: ignore
    ]

    context = {
        "page_obj": page_obj,
        "number_of_products": len(products),
        "starting_number": starting_number,
        "stopping_number": stopping_number,
        "limit": limit,
        "search_term": search_term,
        "pages": pages,
    }
    return render(request, "core/partials/table_search.html", context)


@require_POST
@login_required
@user_passes_test(is_admin)
def update_product_stock(request, product_id):
    product = Product.objects.get(pk=product_id)
    stock = request.POST.get("stock")

    product.stock = stock
    product.save()
    context = {"product": product}
    return render(request, "core/partials/product_table_row.html", context)


@login_required
@user_passes_test(is_admin)
def import_products(request):
    context = {}
    return render(
        request,
        "core/products/import_products.html",
        context,
    )


@require_POST
@login_required
@user_passes_test(is_admin)
def do_import_products(request):
    if bool(request.FILES.get("file")):
        file = io.TextIOWrapper(request.FILES.get("file"))
        csv_reader = csv.DictReader(file)
        rows = [row for row in csv_reader if row.get("PRODUCT") != ""]

        import_task = import_products_task.delay(rows)  # type: ignore
        task_id = import_task.task_id
        progress = Progress(AsyncResult(task_id))
        info = progress.get_info()
        context = {
            "task_id": task_id,
            "info": info,
        }
        return render(request, "core/products/import_products_progress.html", context)
    else:
        context = {"error": "No file submitted"}

        return render(
            request,
            "core/products/import_products.html",
            context,
        )


@login_required
@user_passes_test(is_admin)
def track_import_progress(request, task_id):
    progress = Progress(AsyncResult(task_id))
    info = progress.get_info()

    context = {
        "task_id": task_id,
        "info": info,
    }
    response = render(request, "core/products/import_products_progress.html", context)
    if not info["complete"]:
        return response

    return trigger_client_event(response, "reload_products_table")


@login_required
@user_passes_test(is_admin)
def remove_all_products(request):
    context = {}
    return render(request, "core/products/remove_products_question.html", context)


@login_required
@user_passes_test(is_admin)
def track_remove_product_progress(request, task_id):
    progress = Progress(AsyncResult(task_id))
    info = progress.get_info()

    context = {
        "task_id": task_id,
        "info": info,
    }
    response = render(request, "core/products/remove_products_progress.html", context)
    if not info["complete"]:
        return response

    return trigger_client_event(response, "reload_products_table")


@login_required
@user_passes_test(is_admin)
def get_product_action_buttons(request):
    return render(request, "core/partials/product_action_buttons.html")


@login_required
@user_passes_test(is_admin)
def remove_all_products_question(request):
    context = {"ids": []}
    if request.method == "POST":
        context["ids"] = request.POST.getlist("ids")
    return render(request, "core/products/remove_all_products_question.html", context)


@login_required
@user_passes_test(is_admin)
def do_remove_products(request):
    ids = []
    if request.method == "POST":
        if request.POST.getlist("ids") is not None:
            ids = request.POST.getlist("ids")

    remove_task = remove_products_task.delay(ids)  # type: ignore
    task_id = remove_task.task_id
    progress = Progress(AsyncResult(task_id))
    info = progress.get_info()

    context = {
        "task_id": task_id,
        "info": info,
        "selected_removal": len(ids) > 0,
        "count": len(ids) if len(ids) > 0 else Product.objects.count(),
    }
    return render(request, "core/products/remove_products_progress.html", context)


@login_required
@user_passes_test(is_admin)
def add_product(request):
    form_title = "Enter new product details below"
    form = ProductCreationForm()
    if request.method == "POST":
        form = ProductCreationForm(request.POST)

        if form.is_valid():
            try:
                product = form.save(commit=False)

                if int(form.cleaned_data["cost"]) > 0:
                    product.profit_rate = abs(int(form.cleaned_data["cost"])) / abs(
                        int(form.cleaned_data["price"])
                    )
                else:
                    product.profit_rate = 0
                product.save()
            except Exception as e:
                print(e)
                context = {
                    "type": "danger",
                    "message": "New product could not be saved. Try again later.",
                }
                return render(request, "core/products/response.html", context)
            else:
                context = {
                    "type": "success",
                    "message": "New product successfully saved.",
                }
                response = render(request, "core/products/response.html", context)
                return trigger_client_event(response, "reload_products_table")

    context = {"form": form, "form_title": form_title}
    return render(request, "core/products/new_product.html", context)


@login_required
@user_passes_test(is_admin)
def update_product(request, product_id):
    form_title = "Update product details below"
    product = Product.objects.get(pk=product_id)
    form = ProductCreationForm(instance=product)
    if request.method == "POST":
        form = ProductCreationForm(request.POST, instance=product)
        if form.is_valid():
            try:
                product = form.save(commit=False)
                if int(form.cleaned_data["cost"]) > 0:
                    product.profit_rate = abs(int(form.cleaned_data["cost"])) / abs(
                        int(form.cleaned_data["price"])
                    )
                else:
                    product.profit_rate = 0
                product.save()
            except Exception as e:
                print(e)
                context = {
                    "type": "danger",
                    "message": "The product's update could not be saved. Try again later.",  # noqa: E501
                }
                return render(request, "core/products/response.html", context)
            else:
                context = {
                    "type": "success",
                    "message": "Product successfully updated.",
                }
                response = render(request, "core/products/response.html", context)
                return trigger_client_event(response, "reload_products_table")

    context = {"form": form, "form_title": form_title, "product": product}
    return render(request, "core/products/new_product.html", context)


@login_required
@user_passes_test(is_admin)
def remove_a_product_question(request, product_id):
    product = Product.objects.get(pk=product_id)
    context = {"product": product}
    return render(request, "core/products/remove_a_product_question.html", context)


@login_required
@user_passes_test(is_admin)
def do_remove_a_product(request, product_id):
    product = Product.objects.get(pk=product_id)
    product.delete()
    context = {
        "type": "success",
        "message": f"Product '{product}' successfully removed.",
        "product": product,
    }
    response = render(request, "core/products/response.html", context)
    return trigger_client_event(response, "reload_products_table")


@login_required
@user_passes_test(is_admin)
def orders(request):
    context = {}
    return render(request, "core/orders/orders.html", context)


@login_required
@user_passes_test(is_admin)

core/templates/core/partials/nav.html
<nav class="bg-green-50 border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-800">
  <div class="container flex flex-wrap items-center justify-between mx-auto">
    <a href="{% url 'core:base' %}" class="flex items-center">
      <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white text-yellow-500 font-semibold">Noble Cosmetics</span>
    </a>
    <button data-collapse-toggle="mobile-menu"
            type="button"
            class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
            aria-controls="mobile-menu"
            aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6"
           fill="currentColor"
           viewBox="0 0 20 20"
           xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd">
        </path>
      </svg>
      <svg class="hidden w-6 h-6"
           fill="currentColor"
           viewBox="0 0 20 20"
           xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd">
        </path>
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="mobile-menu">
      <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
        <li>
          <a href="{% url 'core:base' %}"
             class="block py-2 pl-3 pr-4 {% if request.path == '/' %}text-white bg-green-700 md:text-green-700 md:bg-transparent{% endif %} rounded  md:p-0 dark:text-white"
             {% if request.path == '/' %}aria-current="page"{% endif %}>Home</a>
        </li>
        <li>
          <a href="{% url 'core:products' %}"
             class="block py-2 pl-3 pr-4 {% if 'products' in request.path %}text-white bg-green-700 md:text-green-700 md:bg-transparent{% endif %} rounded  md:p-0 dark:text-white"
             {% if 'products' in request.path %}aria-current="page"{% endif %}>Products</a>
        </li>
        <li>
          <a href="{% url 'core:orders' %}"
             class="block py-2 pl-3 pr-4 {% if 'orders/' in request.path %}text-white bg-green-700 md:text-green-700 md:bg-transparent{% endif %} rounded  md:p-0 dark:text-white"
             {% if '/orders' in request.path %}aria-current="page"{% endif %}>Orders</a>
        </li>
        <li>
          <a href="{% url 'auth:logout' %}"
             class="px-3 py-2 font-semibold text-white bg-red-600 rounded-md hover:bg-red-700">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

core/templates/core/partials/product_action_buttons.html
<button type="button"
        hx-get="{% url 'core:load-products' %}?p=1&l=10"
        hx-swap="innerHTML"
        hx-target="#results"
        class="text-white bg-gradient-to-r from-orange-500 via-orange-600 to-orange-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-orange-300 dark:focus:ring-orange-800 shadow-lg shadow-orange-500/50 dark:shadow-lg dark:shadow-orange-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
  All Products
</button>
<button type="button"
        hx-get="{% url 'core:add-product' %}"
        hx-swap="innerHTML"
        hx-target="#new_products"
        class="text-white bg-gradient-to-r from-green-500 via-green-600 to-green-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-green-300 dark:focus:ring-green-800 shadow-lg shadow-green-500/50 dark:shadow-lg dark:shadow-green-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
  Add single product
</button>
<button type="button"
        hx-get="{% url 'core:import-products' %}"
        hx-swap="innerHTML"
        hx-target="#new_products"
        class="text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
  Import new products
</button>
<button x-cloak
        x-show="ids.length === 0"
        type="button"
        hx-get="{% url 'core:remove-products-question' %}"
        hx-swap="innerHTML"
        hx-target="#new_products"
        class="text-white bg-gradient-to-r from-red-500 via-red-600 to-red-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
  Remove all products
</button>
<button x-cloak
        x-show="ids.length > 0"
        type="button"
        hx-post="{% url 'core:remove-products-question' %}"
        hx-swap="innerHTML"
        hx-target="#new_products"
        hx-vals="js:{ids: getProductIDs()}"
        class="text-white bg-gradient-to-r from-red-500 via-red-600 to-red-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
  Remove selected products
</button>
<button hx-swap="innerHTML"
        hx-target="#results"
        hx-get="{% url 'core:out-of-stock' %}"
        class="text-white bg-gradient-to-r from-gray-500 via-gray-600 to-gray-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-gray-300 dark:focus:ring-gray-800 shadow-lg shadow-gray-500/50 dark:shadow-lg dark:shadow-gray-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
  View Out of Stock
</button>
<button hx-swap="innerHTML"
        hx-target="#results"
        hx-get="{% url 'core:products-summary' %}"
        class="text-white bg-gradient-to-r from-teal-500 via-teal-600 to-teal-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-teal-300 dark:focus:ring-teal-800 shadow-lg shadow-teal-500/50 dark:shadow-lg dark:shadow-teal-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ">
  Product Summary
</button>

<script>
  function getProductIDs() {
    const products =  document.querySelectorAll('input[name=products]')
    const ids = []
    for(let i = 0; i<products.length; i++) {
      if (products[i].checked === true) ids.push(products[i].value);
    }
    return ids;

  }
</script>

core/templates/core/partials/product_table_row.html
{% load humanize %}
<tr x-data="{ name: '{{ product.name }}', stock: {{ product.stock }}, subtract: function() { if (this.stock !== 0 ) { this.stock = parseInt(this.stock) - 1; } }, add: function() { this.stock = parseInt(this.stock) + 1; } }"
    id="product_{{ product.id }}"
    class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
  <td class="w-4 p-1.5">
    <div class="flex items-center">
      <input id="checkbox-table-search-1"
             type="checkbox"
             x-model="ids"
             name="products"
             value="{{ product.id }}"
             class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
      <label for="checkbox-table-search-1" class="sr-only">checkbox</label>
    </div>
  </td>
  <th scope="row"
      class="px-3 py-1 font-medium text-gray-900 whitespace-nowrap dark:text-white">{{ product.name }}</th>
  <td class="px-3 py-1">
    <div class="flex items-center space-x-3">
      <button title="Decrease stock count" class="inline-flex items-center p-1 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-full focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"
              type="button"
              @click="subtract()"
              hx-post="{% url 'core:update-product-stock' product.id %}?p={{ page_obj.number }}"
              hx-target="closest tr"
              hx-swap="outerHTML"
              hx-vals="js:{stock:document.querySelector('#product_{{ product.id }}_stock').value}">
        <span class="sr-only">thisQuantity button</span>
        <svg class="w-4 h-4"
             aria-hidden="true"
             fill="currentColor"
             viewBox="0 0 20 20"
             xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path>
        </svg>
      </button>
      <div>
        <input id="product_{{ product.id }}_stock"
               type="number"
               id="qty"
               value="{{ product.stock }}"
               x-model="stock"
               class="bg-gray-50 w-14 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block px-2.5 py-1 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
               placeholder="1"
               min="1"
               required>
      </div>
      <button title="Increase stock count" class="inline-flex items-center p-1 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-full focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"
              type="button"
              @click="add()"
              hx-post="{% url 'core:update-product-stock' product.id %}?p={{ page_obj.number }}"
              hx-target="closest tr"
              hx-swap="outerHTML"
              hx-vals="js:{stock:document.querySelector('#product_{{ product.id }}_stock').value}">
        <span class="sr-only">Quantity button</span>
        <svg class="w-4 h-4"
             aria-hidden="true"
             fill="currentColor"
             viewBox="0 0 20 20"
             xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M10 5a1 1 0 011 1v3h3a1 1 0 110 2h-3v3a1 1 0 11-2 0v-3H6a1 1 0 110-2h3V6a1 1 0 011-1z" clip-rule="evenodd">
          </path>
        </svg>
      </button>
    </div>
  </td>
  <td class="px-3 py-1">GHs{{ product.cost }}</td>
  <td class="px-3 py-1">GHs{{ product.price }}</td>
  <td class="px-3 py-1">{{ product.profit_rate }}</td>
  <td class="px-3 py-1">
    <small>{{ product.updated|naturaltime }}</small>
  </td>
  <td class="flex items-center px-3 py-1 space-x-3">
    <button title="Update this product"  hx-get="{% url 'core:update-product' product.id %}"
            hx-target="#new_products"
            class="text-blue-400 hover:text-blue-600">
      <svg xmlns="http://www.w3.org/2000/svg"
           fill="none"
           viewBox="0 0 24 24"
           stroke-width="1.5"
           stroke="currentColor"
           class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
      </svg>
    </button>
    <button title="Remove this product"  hx-get="{% url 'core:remove-a-product-question' product.id %}"
            hx-target="#new_products"
            class="text-red-400 hover:text-red-600">
      <svg class="w-6 h-6"
           aria-hidden="true"
           fill="currentColor"
           viewBox="0 0 20 20"
           stroke="currentColor"
           stroke-width="1.5"
           xmlns="http://www.w3.org/2000/svg">
        <path d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" stroke-linecap="round" stroke-linejoin="round">
        </path>
      </svg>
    </button>
  </td>
</tr>